services:
  - type: web
    name: portfolio-backend
    runtime: docker
    repo: https://github.com/BernardUriza/portfolio-spring.git
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      # Port configuration - Render will inject this
      # No need to hardcode, let Render handle it
      - key: SPRING_PROFILES_ACTIVE
        value: render
      # Database URL - Render provides DATABASE_URL automatically
      # We need to convert it to JDBC format
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      # These will use the DATABASE_URL via application-render.properties
      # No need to set them explicitly since the app handles conversion
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://localhost:4200,https://*.netlify.app
      # Admin Security - Choose one approach:
      # Option 1: Generate secure token automatically
      - key: ADMIN_TOKEN
        generateValue: true
      # Option 2: For testing only, disable security temporarily
      # - key: APP_ADMIN_SECURITY_DISABLED
      #   value: true
    healthCheckPath: /actuator/health

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free
    region: oregon  # Must match the web service region